### ISSUE TITLE
current_ma, voltage_mv and total_wh not internally consistent

### ISSUE THREAD

**Issue by puterboy** [jkbenaim/hs100#20]
I have a v1 version of the KP125 energy monitoring plug that seems to work fine with hs100 -- i.e., it turns on/off and the emeter functionality responds.

However, some of the emeter numbers are not consistent with the Kasa app.
For example:
```
# hs100 192.168.1.13 emeter
{"emeter":{"get_realtime":{"current_ma":280,"voltage_mv":123141,"power_mw":19871,"total_wh":1374,"err_code":0}}}
```

Now by Watts law, P=IR but `P=19871mw` and `IR = 280 * 123.141 = 34554`
What am I missing here?

**Comment by jkbenaim** [comment]
First: as far as hs100 goes, these numbers are taken directly from the device and passed on to you. If the numbers are wrong, that's a bug in the device, not this program.
Regarding the discrepancy, I think it's due to a power factor of less-than-1. This would explain why the real and apparent power differ.
I don't really know how this device does its measurements, so I can't say for sure.
